Repository swzwij/Proeve-van-Bekwaamheid-2023-2024, pull requests merged in 2024-03, with the labels that each got.

#15 Feature/ad calling
  Assets/Scenes/Develop.unity
  Assets/Scripts/Advertisements/Advertising.cs
  Assets/Scripts/Loading.meta
  Assets/Scripts/Loading/LoadIcon.cs
  Assets/Scripts/Loading/LoadIcon.cs.meta
  Assets/Scripts/Loading/LoadingScreen.cs
  Assets/Scripts/Loading/LoadingScreen.cs.meta
Labels: Ready for review

#17 Feature/dynamic-grounded-check
  Assets/Prefabs/Player/Player.prefab
  Assets/Scripts/Gravity/GravityManager.cs
  Assets/Scripts/Player.meta
  Assets/Scripts/Player/DynamicGroundedCheck.cs
  Assets/Scripts/Player/DynamicGroundedCheck.cs.meta
Labels: Ready for review

#19 Reset the level on generate
  Assets/Scenes/Develop.unity
  Assets/Scripts/Gravity/GravityManager.cs
  Assets/Scripts/Maze/Generation/MazeGenerator.cs
  Assets/Scripts/Spawning.meta
  Assets/Scripts/Spawning/PlayerSpawnPoint.cs
  Assets/Scripts/Spawning/PlayerSpawnPoint.cs.meta
  Assets/Scripts/WorldRotation/WorldRotator.cs
Labels: Ready for review

#25 Added monoscript state setting
  Assets/Scripts/StateMachine/GameStateMachine.cs
  Assets/Scripts/StateMachine/StateMachine.cs
Labels: Ready for review

#24 Feature/pause menu
  Assets/Scenes/MainGame/Game.unity
  Assets/Scenes/MainGame/Pause.unity
  Assets/Scripts/Input/InputSystem.cs
  Assets/Scripts/StateMachine/States/GameState.cs
  Assets/Scripts/StateMachine/States/PausedState.cs
  Assets/Scripts/UI.meta
  Assets/Scripts/UI/Buttons.meta
  Assets/Scripts/UI/Buttons/PauseButton.cs
  Assets/Scripts/UI/Buttons/PauseButton.cs.meta
Labels: Reviewed

#23 Feature/retry level
  Assets/Scenes/MainGame/Game.unity
  Assets/Scripts/Gravity/GravityManager.cs
  Assets/Scripts/Spawning/PlayerSpawnPoint.cs
  Assets/Scripts/UI/Buttons/RetryButton.cs
  Assets/Scripts/UI/Buttons/RetryButton.cs.meta
  Assets/Scripts/WorldRotation/WorldRotator.cs
Labels: Ready for review

#32 Properly reset world rotation when rotating
  Assets/Scripts/WorldRotation/WorldRotator.cs
Labels: bug, Ready for review

#30 Reset player and timer on generate
  Assets/Scenes/MainGame/Game.unity
  Assets/Scripts/Gravity/GravityManager.cs
  Assets/Scripts/Input/SwipeInteraction.cs
  Assets/Scripts/Maze/Generation/GenerationMediator.cs
  Assets/Scripts/Spawning/PlayerSpawnPoint.cs
  Assets/Scripts/Timer/Stopwatch.cs
Labels: Ready for review

#31 Feature/seed input
  Assets/Art/Icons.meta
  Assets/Art/Icons/PlaceHolder.meta
  Assets/Art/Icons/PlaceHolder/Single-Image-Mobile-hazard.png
  Assets/Art/Icons/PlaceHolder/Single-Image-Mobile-hazard.png.meta
  Assets/Scenes/MainGame/Boot.unity
  Assets/Scenes/TestShareSeed.unity
  Assets/Scenes/TestShareSeed.unity.meta
  Assets/Scripts/Maze/Generation/GenerationMediator.cs
  Assets/Scripts/StateMachine/GameStateMachine.cs
  Assets/Scripts/StateMachine/States/GameState.cs
  Assets/Scripts/StateMachine/States/MainMenuState.cs
  Assets/Scripts/StateMachine/States/State.cs
  Assets/Scripts/UI/SeedInput.meta
  Assets/Scripts/UI/SeedInput/SeedInputManager.cs
  Assets/Scripts/UI/SeedInput/SeedInputManager.cs.meta
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
  ProjectSettings/EditorBuildSettings.asset
Labels: Ready for review

#44 Removed unity text in buttons
  Assets/Scenes/MainGame/Game.unity
  Assets/Scenes/MainGame/LevelEnd.unity
  Assets/Scenes/MainGame/MainMenu.unity
  Assets/Scenes/MainGame/Pause.unity
  Assets/Scenes/MainGame/Seed.unity
  Assets/Scenes/MainGame/Share.unity
Labels: Ready for review

#47 Fixed maze deletion on pause
  Assets/Scripts/Maze/Generation/GridGenerator.cs
Labels: Ready for review

#48 Fixed gravity reset bug
  Assets/Prefabs/Systems/GravityManager.prefab
  Assets/Scenes/MainGame/Boot.unity
Labels: Ready for review

#49 Fixed seed input screen
  Assets/Scenes/MainGame/Game.unity
  Assets/Scripts/UI/SeedInput/SeedInputManager.cs
Labels: Ready for review

#51 Fixed coins text not showing up during gameplay
  Assets/Scenes/MainGame/Game.unity
Labels: Ready for review

#54 Fixed unecessary error in Main Menu state
  Assets/Scripts/StateMachine/States/MainMenuState.cs
Labels: Ready for review

#55 Fixed button null reference error for maze generator
  Assets/Scripts/Maze/Generation/GenerationMediator.cs
Labels: Ready for review

#39 Tweaked player teleport position
  Assets/Scenes/MainGame/Game.unity
Labels: Reviewed

#61 Fixed sharescreen text and panel not being correct on all hardware
  Assets/Scenes/MainGame/Share.unity
Labels: Ready for review

#63 Removed toon shader from walls
  Assets/Materials/wall/M_WallTexture.mat
Labels: Ready for review

#66 Fixed timer
  Assets/Scenes/MainGame/Game.unity
Labels: Ready for review

#67 Replaced example readme with wiki homepage text.
  README.md
Labels: Ready for review
